### ISSUE TITLE
Add circleci Continous Integration

### ISSUE THREAD

**Issue by rugwirobaker** [rugwirobaker/shopping-list-app#2]
Add circleci config to with the following workflows:
* test
* build

**Comment by benshidanny11** [comment]
Now I am having blockers with circle ci configurations
**This is the error I am getting**
- =>Error: Package path is not valid. Valid system image paths are:
null
Exited with code 1
**This is the circle.yml content**
- `version: 2
jobs:
  build:
    docker:
      - image: mreichelt/android:28
    working_directory: ~/shopping-list-app
    steps:
      - checkout
      - run: mkdir artifacts
      - run:
          name: List what is currently installed
          command: sdkmanager --list
      - run:
          name: Create AVD
          command: |
            echo "n" | avdmanager -v create avd -n shopping-list-app -k "system-images;android-28;google_apis;armeabi-v7a" -c 512M -g google_apis  -d "Nexus 7 2013"
      - run:
          name: Run Emulator
          background: true
          command: |
            $ANDROID_SDK_ROOT/tools/emulator -no-window -noaudio -no-boot-anim -gpu swiftshader @shopping-list-app
      - run:
          name: Wait for Emulator
          no_output_timeout: 15m
          command: |
            sleep 15
            $ANDROID_SDK_ROOT/platform-tools/adb devices
            sleep 10
      - run:
          name: Fetch logcat and props
          background: true
          command: |
            $ANDROID_SDK_ROOT/platform-tools/adb logcat >> ./artifacts/logcat.txt
            $ANDROID_SDK_ROOT/platform-tools/adb shell getprop >> ./artifacts/props.txt
      - run:
          name: Run Android Connected Tests
          command: |
            export ADB_INSTALL_TIMEOUT=120
            export ANDROID_HOME=$ANDROID_SDK_ROOT
            # ./scripts/test.sh
            ./gradlew assembleDebug
            # Wait for emulator to fully boot
            # TODO: Need to create a good check
            sleep 60
            # Is the emulator still running?
            adb devices
            # Check if package manager is running
            adb shell pm list packages
            # Install package
            $ANDROID_SDK_ROOT/platform-tools/adb install /home/android/shopping-list-app/app/build/outputs/apk/app-debug.apk
            ./gradlew connectedAndroidTest
      - store_artifacts:
          path: ~/shopping-list-app/artifacts
          destination: env`

_And, to be honest, this is my first time to integrate circle ci to the git repo_
- You can help me to understand how it works if possible.
**Here is the link**
- https://circleci.com/gh/benshidanny11/shopping-list-app/20

**Comment by rugwirobaker** [comment]
## solve invalid path issue in create avd step
**command :**
`echo "n" | avdmanager -v create avd -n shopping-list-app -k "system-images;android-28;google_apis;armeabi-v7a" -c 512M -g google_apis  -d "Nexus 7 2013"`

**output:**
Loading local repository...                                                     
Error: Package path is not valid. Valid system image paths are:
null
Exited with code 1

Can  this help:https://circleci.com/docs/2.0/language-android/

**Comment by rugwirobaker** [comment]
https://circleci.com/docs/2.0/language-android/

**Comment by benshidanny11** [comment]
_I am done with error resolving, you can check via this link_
- [Here](https://circleci.com/gh/benshidanny11/shopping-list-app/tree/develop)

**Comment by rugwirobaker** [comment]
Solved by: https://github.com/rugwirobaker/shopping-list-app/pull/6#issue-289832025
